-- ===========================================================================
-- FK patch — schema 'commerce'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- commerce.coupon_redemptions ----------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:254)
DO $$ BEGIN
    ALTER TABLE commerce.coupon_redemptions
        ADD CONSTRAINT coupon_redemptions_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_brand_id_fk
    ON commerce.coupon_redemptions (brand_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:255)
DO $$ BEGIN
    ALTER TABLE commerce.coupon_redemptions
        ADD CONSTRAINT coupon_redemptions_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_customer_id_fk
    ON commerce.coupon_redemptions (customer_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:256)
DO $$ BEGIN
    ALTER TABLE commerce.coupon_redemptions
        ADD CONSTRAINT coupon_redemptions_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_order_id_fk
    ON commerce.coupon_redemptions (order_id, order_created_at);

-- ---- commerce.customer_packages -----------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:77)
DO $$ BEGIN
    ALTER TABLE commerce.customer_packages
        ADD CONSTRAINT customer_packages_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_customer_packages_brand_id_fk
    ON commerce.customer_packages (brand_id);

-- bucket S: soft pointer — parent may be deleted/cancelled (src 06_bc6_commerce.sql:82)
DO $$ BEGIN
    ALTER TABLE commerce.customer_packages
        ADD CONSTRAINT customer_packages_payment_id_fkey
        FOREIGN KEY (payment_id)
        REFERENCES commerce.payments(id)
        ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_customer_packages_payment_id_fk
    ON commerce.customer_packages (payment_id);

-- ---- commerce.loyalty_points_ledger -------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:175)
DO $$ BEGIN
    ALTER TABLE commerce.loyalty_points_ledger
        ADD CONSTRAINT loyalty_points_ledger_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_loyalty_points_ledger_brand_id_fk
    ON commerce.loyalty_points_ledger (brand_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:187)
DO $$ BEGIN
    ALTER TABLE commerce.loyalty_points_ledger
        ADD CONSTRAINT loyalty_points_ledger_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_loyalty_points_ledger_order_id_fk
    ON commerce.loyalty_points_ledger (order_id, order_created_at);

-- ---- commerce.package_usage_ledger --------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:115)
DO $$ BEGIN
    ALTER TABLE commerce.package_usage_ledger
        ADD CONSTRAINT package_usage_ledger_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_package_usage_ledger_brand_id_fk
    ON commerce.package_usage_ledger (brand_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:116)
DO $$ BEGIN
    ALTER TABLE commerce.package_usage_ledger
        ADD CONSTRAINT package_usage_ledger_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_package_usage_ledger_customer_id_fk
    ON commerce.package_usage_ledger (customer_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:117)
DO $$ BEGIN
    ALTER TABLE commerce.package_usage_ledger
        ADD CONSTRAINT package_usage_ledger_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_package_usage_ledger_order_id_fk
    ON commerce.package_usage_ledger (order_id, order_created_at);

-- ---- commerce.payment_refunds -------------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:412)
DO $$ BEGIN
    ALTER TABLE commerce.payment_refunds
        ADD CONSTRAINT payment_refunds_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payment_refunds_brand_id_fk
    ON commerce.payment_refunds (brand_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:414)
DO $$ BEGIN
    ALTER TABLE commerce.payment_refunds
        ADD CONSTRAINT payment_refunds_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payment_refunds_order_id_fk
    ON commerce.payment_refunds (order_id, order_created_at);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:416)
DO $$ BEGIN
    ALTER TABLE commerce.payment_refunds
        ADD CONSTRAINT payment_refunds_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payment_refunds_customer_id_fk
    ON commerce.payment_refunds (customer_id);

-- ---- commerce.payments --------------------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:354)
DO $$ BEGIN
    ALTER TABLE commerce.payments
        ADD CONSTRAINT payments_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payments_brand_id_fk
    ON commerce.payments (brand_id);

-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:355)
DO $$ BEGIN
    ALTER TABLE commerce.payments
        ADD CONSTRAINT payments_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payments_franchise_id_fk
    ON commerce.payments (franchise_id);

-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:356)
DO $$ BEGIN
    ALTER TABLE commerce.payments
        ADD CONSTRAINT payments_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payments_store_id_fk
    ON commerce.payments (store_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:357)
DO $$ BEGIN
    ALTER TABLE commerce.payments
        ADD CONSTRAINT payments_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payments_customer_id_fk
    ON commerce.payments (customer_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:358)
DO $$ BEGIN
    ALTER TABLE commerce.payments
        ADD CONSTRAINT payments_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_payments_order_id_fk
    ON commerce.payments (order_id, order_created_at);

-- ---- commerce.wallet_accounts -------------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:451)
DO $$ BEGIN
    ALTER TABLE commerce.wallet_accounts
        ADD CONSTRAINT wallet_accounts_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_wallet_accounts_brand_id_fk
    ON commerce.wallet_accounts (brand_id);

-- ---- commerce.wallet_transactions ---------------------------------------
-- bucket 2: tenant scoping (src 06_bc6_commerce.sql:479)
DO $$ BEGIN
    ALTER TABLE commerce.wallet_transactions
        ADD CONSTRAINT wallet_transactions_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_brand_id_fk
    ON commerce.wallet_transactions (brand_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:480)
DO $$ BEGIN
    ALTER TABLE commerce.wallet_transactions
        ADD CONSTRAINT wallet_transactions_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_customer_id_fk
    ON commerce.wallet_transactions (customer_id);

-- bucket 1: domain cross-aggregate link (src 06_bc6_commerce.sql:489)
DO $$ BEGIN
    ALTER TABLE commerce.wallet_transactions
        ADD CONSTRAINT wallet_transactions_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_order_id_fk
    ON commerce.wallet_transactions (order_id, order_created_at);

-- bucket S: soft pointer — parent may be deleted/cancelled (src 06_bc6_commerce.sql:491)
DO $$ BEGIN
    ALTER TABLE commerce.wallet_transactions
        ADD CONSTRAINT wallet_transactions_payment_id_fkey
        FOREIGN KEY (payment_id)
        REFERENCES commerce.payments(id)
        ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_payment_id_fk
    ON commerce.wallet_transactions (payment_id);

-- bucket S: soft pointer — parent may be deleted/cancelled (src 06_bc6_commerce.sql:492)
DO $$ BEGIN
    ALTER TABLE commerce.wallet_transactions
        ADD CONSTRAINT wallet_transactions_refund_id_fkey
        FOREIGN KEY (refund_id)
        REFERENCES commerce.payment_refunds(id)
        ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_refund_id_fk
    ON commerce.wallet_transactions (refund_id);

