-- ===========================================================================
-- FK patch — schema 'finance_royalty'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- finance_royalty.cash_book_entries ----------------------------------
-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:75)
DO $$ BEGIN
    ALTER TABLE finance_royalty.cash_book_entries
        ADD CONSTRAINT cash_book_entries_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_cash_book_entries_brand_id_fk
    ON finance_royalty.cash_book_entries (brand_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:76)
DO $$ BEGIN
    ALTER TABLE finance_royalty.cash_book_entries
        ADD CONSTRAINT cash_book_entries_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_cash_book_entries_store_id_fk
    ON finance_royalty.cash_book_entries (store_id);

-- bucket 1: domain cross-aggregate link (src 07_bc7_finance_royalty.sql:88)
DO $$ BEGIN
    ALTER TABLE finance_royalty.cash_book_entries
        ADD CONSTRAINT cash_book_entries_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_cash_book_entries_order_id_fk
    ON finance_royalty.cash_book_entries (order_id, order_created_at);

-- bucket 1: domain cross-aggregate link (src 07_bc7_finance_royalty.sql:91)
DO $$ BEGIN
    ALTER TABLE finance_royalty.cash_book_entries
        ADD CONSTRAINT cash_book_entries_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_cash_book_entries_customer_id_fk
    ON finance_royalty.cash_book_entries (customer_id);

-- ---- finance_royalty.cash_books -----------------------------------------
-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:26)
DO $$ BEGIN
    ALTER TABLE finance_royalty.cash_books
        ADD CONSTRAINT cash_books_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_cash_books_brand_id_fk
    ON finance_royalty.cash_books (brand_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:27)
DO $$ BEGIN
    ALTER TABLE finance_royalty.cash_books
        ADD CONSTRAINT cash_books_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_cash_books_franchise_id_fk
    ON finance_royalty.cash_books (franchise_id);

-- ---- finance_royalty.expense_attachments --------------------------------
-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:198)
DO $$ BEGIN
    ALTER TABLE finance_royalty.expense_attachments
        ADD CONSTRAINT expense_attachments_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_expense_attachments_brand_id_fk
    ON finance_royalty.expense_attachments (brand_id);

-- ---- finance_royalty.expenses -------------------------------------------
-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:144)
DO $$ BEGIN
    ALTER TABLE finance_royalty.expenses
        ADD CONSTRAINT expenses_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_expenses_brand_id_fk
    ON finance_royalty.expenses (brand_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:145)
DO $$ BEGIN
    ALTER TABLE finance_royalty.expenses
        ADD CONSTRAINT expenses_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_expenses_franchise_id_fk
    ON finance_royalty.expenses (franchise_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:146)
DO $$ BEGIN
    ALTER TABLE finance_royalty.expenses
        ADD CONSTRAINT expenses_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_expenses_store_id_fk
    ON finance_royalty.expenses (store_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:147)
DO $$ BEGIN
    ALTER TABLE finance_royalty.expenses
        ADD CONSTRAINT expenses_warehouse_id_fkey
        FOREIGN KEY (warehouse_id)
        REFERENCES tenancy_org.warehouses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_expenses_warehouse_id_fk
    ON finance_royalty.expenses (warehouse_id);

-- bucket 1: domain cross-aggregate link (src 07_bc7_finance_royalty.sql:149)
DO $$ BEGIN
    ALTER TABLE finance_royalty.expenses
        ADD CONSTRAINT expenses_cash_book_entry_id_fkey
        FOREIGN KEY (cash_book_entry_id)
        REFERENCES finance_royalty.cash_book_entries(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_expenses_cash_book_entry_id_fk
    ON finance_royalty.expenses (cash_book_entry_id);

-- ---- finance_royalty.royalty_calculations -------------------------------
-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:312)
DO $$ BEGIN
    ALTER TABLE finance_royalty.royalty_calculations
        ADD CONSTRAINT royalty_calculations_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_royalty_calculations_brand_id_fk
    ON finance_royalty.royalty_calculations (brand_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:313)
DO $$ BEGIN
    ALTER TABLE finance_royalty.royalty_calculations
        ADD CONSTRAINT royalty_calculations_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_royalty_calculations_franchise_id_fk
    ON finance_royalty.royalty_calculations (franchise_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:314)
DO $$ BEGIN
    ALTER TABLE finance_royalty.royalty_calculations
        ADD CONSTRAINT royalty_calculations_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_royalty_calculations_store_id_fk
    ON finance_royalty.royalty_calculations (store_id);

-- bucket 1: domain cross-aggregate link (src 07_bc7_finance_royalty.sql:315)
DO $$ BEGIN
    ALTER TABLE finance_royalty.royalty_calculations
        ADD CONSTRAINT royalty_calculations_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_royalty_calculations_order_id_fk
    ON finance_royalty.royalty_calculations (order_id, order_created_at);

-- bucket 1: domain cross-aggregate link (src 07_bc7_finance_royalty.sql:318)
DO $$ BEGIN
    ALTER TABLE finance_royalty.royalty_calculations
        ADD CONSTRAINT royalty_calculations_service_category_id_fkey
        FOREIGN KEY (service_category_id)
        REFERENCES customer_catalog.service_categories(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_royalty_calculations_service_category_id_fk
    ON finance_royalty.royalty_calculations (service_category_id);

-- ---- finance_royalty.royalty_invoices -----------------------------------
-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:257)
DO $$ BEGIN
    ALTER TABLE finance_royalty.royalty_invoices
        ADD CONSTRAINT royalty_invoices_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_royalty_invoices_brand_id_fk
    ON finance_royalty.royalty_invoices (brand_id);

-- ---- finance_royalty.shift_handovers ------------------------------------
-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:221)
DO $$ BEGIN
    ALTER TABLE finance_royalty.shift_handovers
        ADD CONSTRAINT shift_handovers_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_shift_handovers_brand_id_fk
    ON finance_royalty.shift_handovers (brand_id);

-- bucket 2: tenant scoping (src 07_bc7_finance_royalty.sql:222)
DO $$ BEGIN
    ALTER TABLE finance_royalty.shift_handovers
        ADD CONSTRAINT shift_handovers_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_shift_handovers_store_id_fk
    ON finance_royalty.shift_handovers (store_id);

