-- ===========================================================================
-- FK patch — schema 'order_lifecycle'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- order_lifecycle.delivery_assignments -------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:297)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_assignments
        ADD CONSTRAINT delivery_assignments_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_assignments_brand_id_fk
    ON order_lifecycle.delivery_assignments (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:298)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_assignments
        ADD CONSTRAINT delivery_assignments_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_assignments_store_id_fk
    ON order_lifecycle.delivery_assignments (store_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:299)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_assignments
        ADD CONSTRAINT delivery_assignments_rider_id_fkey
        FOREIGN KEY (rider_id)
        REFERENCES logistics.riders(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_assignments_rider_id_fk
    ON order_lifecycle.delivery_assignments (rider_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:300)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_assignments
        ADD CONSTRAINT delivery_assignments_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_assignments_order_id_fk
    ON order_lifecycle.delivery_assignments (order_id, order_created_at);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:302)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_assignments
        ADD CONSTRAINT delivery_assignments_pickup_request_id_fkey
        FOREIGN KEY (pickup_request_id)
        REFERENCES order_lifecycle.pickup_requests(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_assignments_pickup_request_id_fk
    ON order_lifecycle.delivery_assignments (pickup_request_id);

-- ---- order_lifecycle.delivery_slot_bookings -----------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:373)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_slot_bookings
        ADD CONSTRAINT delivery_slot_bookings_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_slot_bookings_brand_id_fk
    ON order_lifecycle.delivery_slot_bookings (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:374)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_slot_bookings
        ADD CONSTRAINT delivery_slot_bookings_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_slot_bookings_store_id_fk
    ON order_lifecycle.delivery_slot_bookings (store_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:375)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_slot_bookings
        ADD CONSTRAINT delivery_slot_bookings_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_slot_bookings_order_id_fk
    ON order_lifecycle.delivery_slot_bookings (order_id, order_created_at);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:377)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_slot_bookings
        ADD CONSTRAINT delivery_slot_bookings_pickup_request_id_fkey
        FOREIGN KEY (pickup_request_id)
        REFERENCES order_lifecycle.pickup_requests(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_slot_bookings_pickup_request_id_fk
    ON order_lifecycle.delivery_slot_bookings (pickup_request_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:378)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_slot_bookings
        ADD CONSTRAINT delivery_slot_bookings_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_slot_bookings_customer_id_fk
    ON order_lifecycle.delivery_slot_bookings (customer_id);

-- ---- order_lifecycle.delivery_slots -------------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:342)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.delivery_slots
        ADD CONSTRAINT delivery_slots_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_delivery_slots_brand_id_fk
    ON order_lifecycle.delivery_slots (brand_id);

-- ---- order_lifecycle.garment_inspection_photos --------------------------
-- bucket C: aggregate child of garments (src 04_bc4_order_lifecycle.sql:536)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garment_inspection_photos
        ADD CONSTRAINT garment_inspection_photos_garment_id_fkey
        FOREIGN KEY (garment_id)
        REFERENCES order_lifecycle.garments(id)
        ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garment_inspection_photo_garment_id_fk
    ON order_lifecycle.garment_inspection_photos (garment_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:537)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garment_inspection_photos
        ADD CONSTRAINT garment_inspection_photos_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garment_inspection_photo_brand_id_fk
    ON order_lifecycle.garment_inspection_photos (brand_id);

-- ---- order_lifecycle.garment_inspections --------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:496)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garment_inspections
        ADD CONSTRAINT garment_inspections_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garment_inspections_brand_id_fk
    ON order_lifecycle.garment_inspections (brand_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:498)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garment_inspections
        ADD CONSTRAINT garment_inspections_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garment_inspections_order_id_fk
    ON order_lifecycle.garment_inspections (order_id, order_created_at);

-- ---- order_lifecycle.garment_tags ---------------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:466)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garment_tags
        ADD CONSTRAINT garment_tags_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garment_tags_brand_id_fk
    ON order_lifecycle.garment_tags (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:467)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garment_tags
        ADD CONSTRAINT garment_tags_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garment_tags_store_id_fk
    ON order_lifecycle.garment_tags (store_id);

-- ---- order_lifecycle.garments -------------------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:401)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garments
        ADD CONSTRAINT garments_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garments_brand_id_fk
    ON order_lifecycle.garments (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:402)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garments
        ADD CONSTRAINT garments_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garments_franchise_id_fk
    ON order_lifecycle.garments (franchise_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:403)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garments
        ADD CONSTRAINT garments_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garments_store_id_fk
    ON order_lifecycle.garments (store_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:404)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garments
        ADD CONSTRAINT garments_warehouse_id_fkey
        FOREIGN KEY (warehouse_id)
        REFERENCES tenancy_org.warehouses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garments_warehouse_id_fk
    ON order_lifecycle.garments (warehouse_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:405)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garments
        ADD CONSTRAINT garments_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garments_order_id_fk
    ON order_lifecycle.garments (order_id, order_created_at);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:408)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.garments
        ADD CONSTRAINT garments_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_garments_customer_id_fk
    ON order_lifecycle.garments (customer_id);

-- ---- order_lifecycle.order_addons ---------------------------------------
-- bucket C: aggregate child of orders (src 04_bc4_order_lifecycle.sql:181)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_addons
        ADD CONSTRAINT order_addons_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_addons_order_id_fk
    ON order_lifecycle.order_addons (order_id, order_created_at);

-- ---- order_lifecycle.order_items ----------------------------------------
-- bucket C: aggregate child of orders (src 04_bc4_order_lifecycle.sql:141)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_items
        ADD CONSTRAINT order_items_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_items_order_id_fk
    ON order_lifecycle.order_items (order_id, order_created_at);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:143)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_items
        ADD CONSTRAINT order_items_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_items_brand_id_fk
    ON order_lifecycle.order_items (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:144)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_items
        ADD CONSTRAINT order_items_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_items_store_id_fk
    ON order_lifecycle.order_items (store_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:150)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_items
        ADD CONSTRAINT order_items_price_list_item_id_fkey
        FOREIGN KEY (price_list_item_id)
        REFERENCES customer_catalog.price_list_items(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_items_price_list_item_id_fk
    ON order_lifecycle.order_items (price_list_item_id);

-- ---- order_lifecycle.order_notes ----------------------------------------
-- bucket C: aggregate child of orders (src 04_bc4_order_lifecycle.sql:230)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_notes
        ADD CONSTRAINT order_notes_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_notes_order_id_fk
    ON order_lifecycle.order_notes (order_id, order_created_at);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:232)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_notes
        ADD CONSTRAINT order_notes_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_notes_brand_id_fk
    ON order_lifecycle.order_notes (brand_id);

-- ---- order_lifecycle.order_status_history -------------------------------
-- bucket C: aggregate child of orders (src 04_bc4_order_lifecycle.sql:202)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_status_history
        ADD CONSTRAINT order_status_history_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id_fk
    ON order_lifecycle.order_status_history (order_id, order_created_at);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:204)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.order_status_history
        ADD CONSTRAINT order_status_history_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_order_status_history_brand_id_fk
    ON order_lifecycle.order_status_history (brand_id);

-- ---- order_lifecycle.orders ---------------------------------------------
-- bucket 3: tenant scoping (partitioned referencing table) (src 04_bc4_order_lifecycle.sql:26)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_brand_id_fk
    ON order_lifecycle.orders (brand_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 04_bc4_order_lifecycle.sql:27)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_franchise_id_fk
    ON order_lifecycle.orders (franchise_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 04_bc4_order_lifecycle.sql:28)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_store_id_fk
    ON order_lifecycle.orders (store_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 04_bc4_order_lifecycle.sql:29)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_warehouse_id_fkey
        FOREIGN KEY (warehouse_id)
        REFERENCES tenancy_org.warehouses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_warehouse_id_fk
    ON order_lifecycle.orders (warehouse_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:30)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_customer_id_fk
    ON order_lifecycle.orders (customer_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:31)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_pickup_address_id_fkey
        FOREIGN KEY (pickup_address_id)
        REFERENCES customer_catalog.customer_addresses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_pickup_address_id_fk
    ON order_lifecycle.orders (pickup_address_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:32)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_delivery_address_id_fkey
        FOREIGN KEY (delivery_address_id)
        REFERENCES customer_catalog.customer_addresses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_delivery_address_id_fk
    ON order_lifecycle.orders (delivery_address_id);

-- bucket S: soft pointer — parent may be deleted/cancelled (src 04_bc4_order_lifecycle.sql:33)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_pickup_slot_id_fkey
        FOREIGN KEY (pickup_slot_id)
        REFERENCES order_lifecycle.delivery_slots(id)
        ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_pickup_slot_id_fk
    ON order_lifecycle.orders (pickup_slot_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:35)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_pickup_rider_id_fkey
        FOREIGN KEY (pickup_rider_id)
        REFERENCES logistics.riders(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_pickup_rider_id_fk
    ON order_lifecycle.orders (pickup_rider_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:36)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_delivery_rider_id_fkey
        FOREIGN KEY (delivery_rider_id)
        REFERENCES logistics.riders(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_delivery_rider_id_fk
    ON order_lifecycle.orders (delivery_rider_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:68)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_coupon_id_fkey
        FOREIGN KEY (coupon_id)
        REFERENCES commerce.coupons(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_coupon_id_fk
    ON order_lifecycle.orders (coupon_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:70)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_package_id_fkey
        FOREIGN KEY (package_id)
        REFERENCES commerce.packages(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_package_id_fk
    ON order_lifecycle.orders (package_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:71)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.orders
        ADD CONSTRAINT orders_customer_package_id_fkey
        FOREIGN KEY (customer_package_id)
        REFERENCES commerce.customer_packages(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_orders_customer_package_id_fk
    ON order_lifecycle.orders (customer_package_id);

-- ---- order_lifecycle.pickup_requests ------------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:258)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.pickup_requests
        ADD CONSTRAINT pickup_requests_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_pickup_requests_brand_id_fk
    ON order_lifecycle.pickup_requests (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:259)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.pickup_requests
        ADD CONSTRAINT pickup_requests_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_pickup_requests_franchise_id_fk
    ON order_lifecycle.pickup_requests (franchise_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:260)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.pickup_requests
        ADD CONSTRAINT pickup_requests_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_pickup_requests_store_id_fk
    ON order_lifecycle.pickup_requests (store_id);

-- ---- order_lifecycle.process_logs ---------------------------------------
-- bucket 3: tenant scoping (partitioned referencing table) (src 04_bc4_order_lifecycle.sql:664)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.process_logs
        ADD CONSTRAINT process_logs_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_process_logs_brand_id_fk
    ON order_lifecycle.process_logs (brand_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 04_bc4_order_lifecycle.sql:665)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.process_logs
        ADD CONSTRAINT process_logs_warehouse_id_fkey
        FOREIGN KEY (warehouse_id)
        REFERENCES tenancy_org.warehouses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_process_logs_warehouse_id_fk
    ON order_lifecycle.process_logs (warehouse_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:666)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.process_logs
        ADD CONSTRAINT process_logs_batch_id_fkey
        FOREIGN KEY (batch_id)
        REFERENCES order_lifecycle.warehouse_batches(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_process_logs_batch_id_fk
    ON order_lifecycle.process_logs (batch_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:667)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.process_logs
        ADD CONSTRAINT process_logs_garment_id_fkey
        FOREIGN KEY (garment_id)
        REFERENCES order_lifecycle.garments(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_process_logs_garment_id_fk
    ON order_lifecycle.process_logs (garment_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:669)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.process_logs
        ADD CONSTRAINT process_logs_process_id_fkey
        FOREIGN KEY (process_id)
        REFERENCES order_lifecycle.warehouse_processes(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_process_logs_process_id_fk
    ON order_lifecycle.process_logs (process_id);

-- ---- order_lifecycle.quality_checks -------------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:696)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.quality_checks
        ADD CONSTRAINT quality_checks_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_quality_checks_brand_id_fk
    ON order_lifecycle.quality_checks (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:697)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.quality_checks
        ADD CONSTRAINT quality_checks_warehouse_id_fkey
        FOREIGN KEY (warehouse_id)
        REFERENCES tenancy_org.warehouses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_quality_checks_warehouse_id_fk
    ON order_lifecycle.quality_checks (warehouse_id);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:699)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.quality_checks
        ADD CONSTRAINT quality_checks_order_id_fkey
        FOREIGN KEY (order_id, order_created_at)
        REFERENCES order_lifecycle.orders(id, created_at)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_quality_checks_order_id_fk
    ON order_lifecycle.quality_checks (order_id, order_created_at);

-- bucket 1: domain cross-aggregate link (src 04_bc4_order_lifecycle.sql:701)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.quality_checks
        ADD CONSTRAINT quality_checks_batch_id_fkey
        FOREIGN KEY (batch_id)
        REFERENCES order_lifecycle.warehouse_batches(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_quality_checks_batch_id_fk
    ON order_lifecycle.quality_checks (batch_id);

-- ---- order_lifecycle.stock_reconciliation_items -------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:775)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.stock_reconciliation_items
        ADD CONSTRAINT stock_reconciliation_items_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_stock_reconciliation_ite_brand_id_fk
    ON order_lifecycle.stock_reconciliation_items (brand_id);

-- ---- order_lifecycle.stock_reconciliations ------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:735)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.stock_reconciliations
        ADD CONSTRAINT stock_reconciliations_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_stock_reconciliations_brand_id_fk
    ON order_lifecycle.stock_reconciliations (brand_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:736)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.stock_reconciliations
        ADD CONSTRAINT stock_reconciliations_warehouse_id_fkey
        FOREIGN KEY (warehouse_id)
        REFERENCES tenancy_org.warehouses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_stock_reconciliations_warehouse_id_fk
    ON order_lifecycle.stock_reconciliations (warehouse_id);

-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:737)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.stock_reconciliations
        ADD CONSTRAINT stock_reconciliations_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_stock_reconciliations_store_id_fk
    ON order_lifecycle.stock_reconciliations (store_id);

-- ---- order_lifecycle.warehouse_batches ----------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:602)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.warehouse_batches
        ADD CONSTRAINT warehouse_batches_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_warehouse_batches_brand_id_fk
    ON order_lifecycle.warehouse_batches (brand_id);

-- ---- order_lifecycle.warehouse_processes --------------------------------
-- bucket 2: tenant scoping (src 04_bc4_order_lifecycle.sql:639)
DO $$ BEGIN
    ALTER TABLE order_lifecycle.warehouse_processes
        ADD CONSTRAINT warehouse_processes_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_warehouse_processes_brand_id_fk
    ON order_lifecycle.warehouse_processes (brand_id);

