-- ===========================================================================
-- FK patch — schema 'identity_access'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- identity_access.audit_logs -----------------------------------------
-- bucket 3: tenant scoping (partitioned referencing table) (src 02_bc2_identity_access.sql:299)
DO $$ BEGIN
    ALTER TABLE identity_access.audit_logs
        ADD CONSTRAINT audit_logs_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_audit_logs_brand_id_fk
    ON identity_access.audit_logs (brand_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 02_bc2_identity_access.sql:300)
DO $$ BEGIN
    ALTER TABLE identity_access.audit_logs
        ADD CONSTRAINT audit_logs_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_audit_logs_franchise_id_fk
    ON identity_access.audit_logs (franchise_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 02_bc2_identity_access.sql:301)
DO $$ BEGIN
    ALTER TABLE identity_access.audit_logs
        ADD CONSTRAINT audit_logs_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_audit_logs_store_id_fk
    ON identity_access.audit_logs (store_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 02_bc2_identity_access.sql:302)
DO $$ BEGIN
    ALTER TABLE identity_access.audit_logs
        ADD CONSTRAINT audit_logs_warehouse_id_fkey
        FOREIGN KEY (warehouse_id)
        REFERENCES tenancy_org.warehouses(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_audit_logs_warehouse_id_fk
    ON identity_access.audit_logs (warehouse_id);

-- ---- identity_access.login_history --------------------------------------
-- bucket 1: domain cross-aggregate link (src 02_bc2_identity_access.sql:271)
DO $$ BEGIN
    ALTER TABLE identity_access.login_history
        ADD CONSTRAINT login_history_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_login_history_customer_id_fk
    ON identity_access.login_history (customer_id);

-- ---- identity_access.otp_codes ------------------------------------------
-- bucket 1: domain cross-aggregate link (src 02_bc2_identity_access.sql:220)
DO $$ BEGIN
    ALTER TABLE identity_access.otp_codes
        ADD CONSTRAINT otp_codes_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_otp_codes_customer_id_fk
    ON identity_access.otp_codes (customer_id);

-- ---- identity_access.password_resets ------------------------------------
-- bucket 1: domain cross-aggregate link (src 02_bc2_identity_access.sql:338)
DO $$ BEGIN
    ALTER TABLE identity_access.password_resets
        ADD CONSTRAINT password_resets_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_password_resets_customer_id_fk
    ON identity_access.password_resets (customer_id);

-- ---- identity_access.refresh_tokens -------------------------------------
-- bucket 1: domain cross-aggregate link (src 02_bc2_identity_access.sql:241)
DO $$ BEGIN
    ALTER TABLE identity_access.refresh_tokens
        ADD CONSTRAINT refresh_tokens_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_customer_id_fk
    ON identity_access.refresh_tokens (customer_id);

