-- ===========================================================================
-- FK patch — schema 'customer_catalog'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- customer_catalog.account_deletion_requests -------------------------
-- bucket 2: tenant scoping (src 03_bc3_customer_catalog.sql:170)
DO $$ BEGIN
    ALTER TABLE customer_catalog.account_deletion_requests
        ADD CONSTRAINT account_deletion_requests_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_account_deletion_request_brand_id_fk
    ON customer_catalog.account_deletion_requests (brand_id);

-- ---- customer_catalog.customer_addresses --------------------------------
-- bucket 2: tenant scoping (src 03_bc3_customer_catalog.sql:93)
DO $$ BEGIN
    ALTER TABLE customer_catalog.customer_addresses
        ADD CONSTRAINT customer_addresses_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_customer_addresses_brand_id_fk
    ON customer_catalog.customer_addresses (brand_id);

-- ---- customer_catalog.customer_devices ----------------------------------
-- bucket 2: tenant scoping (src 03_bc3_customer_catalog.sql:137)
DO $$ BEGIN
    ALTER TABLE customer_catalog.customer_devices
        ADD CONSTRAINT customer_devices_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_customer_devices_brand_id_fk
    ON customer_catalog.customer_devices (brand_id);

-- ---- customer_catalog.dpdp_consents -------------------------------------
-- bucket 2: tenant scoping (src 03_bc3_customer_catalog.sql:209)
DO $$ BEGIN
    ALTER TABLE customer_catalog.dpdp_consents
        ADD CONSTRAINT dpdp_consents_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_dpdp_consents_brand_id_fk
    ON customer_catalog.dpdp_consents (brand_id);

-- ---- customer_catalog.price_list_items ----------------------------------
-- bucket 2: tenant scoping (src 03_bc3_customer_catalog.sql:494)
DO $$ BEGIN
    ALTER TABLE customer_catalog.price_list_items
        ADD CONSTRAINT price_list_items_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_price_list_items_brand_id_fk
    ON customer_catalog.price_list_items (brand_id);

