-- ===========================================================================
-- FK patch — schema 'logistics'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- logistics.rider_assignments ----------------------------------------
-- bucket 2: tenant scoping (src 05_bc5_logistics.sql:84)
DO $$ BEGIN
    ALTER TABLE logistics.rider_assignments
        ADD CONSTRAINT rider_assignments_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_rider_assignments_brand_id_fk
    ON logistics.rider_assignments (brand_id);

-- bucket 2: tenant scoping (src 05_bc5_logistics.sql:85)
DO $$ BEGIN
    ALTER TABLE logistics.rider_assignments
        ADD CONSTRAINT rider_assignments_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_rider_assignments_store_id_fk
    ON logistics.rider_assignments (store_id);

-- ---- logistics.rider_capacity_config ------------------------------------
-- bucket 2: tenant scoping (src 05_bc5_logistics.sql:142)
DO $$ BEGIN
    ALTER TABLE logistics.rider_capacity_config
        ADD CONSTRAINT rider_capacity_config_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_rider_capacity_config_brand_id_fk
    ON logistics.rider_capacity_config (brand_id);

-- bucket 2: tenant scoping (src 05_bc5_logistics.sql:143)
DO $$ BEGIN
    ALTER TABLE logistics.rider_capacity_config
        ADD CONSTRAINT rider_capacity_config_store_id_fkey
        FOREIGN KEY (store_id)
        REFERENCES tenancy_org.stores(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_rider_capacity_config_store_id_fk
    ON logistics.rider_capacity_config (store_id);

-- ---- logistics.rider_location_pings -------------------------------------
-- bucket C: aggregate child of riders (src 05_bc5_logistics.sql:116)
DO $$ BEGIN
    ALTER TABLE logistics.rider_location_pings
        ADD CONSTRAINT rider_location_pings_rider_id_fkey
        FOREIGN KEY (rider_id)
        REFERENCES logistics.riders(id)
        ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_rider_location_pings_rider_id_fk
    ON logistics.rider_location_pings (rider_id);

-- bucket 3: tenant scoping (partitioned referencing table) (src 05_bc5_logistics.sql:117)
DO $$ BEGIN
    ALTER TABLE logistics.rider_location_pings
        ADD CONSTRAINT rider_location_pings_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_rider_location_pings_brand_id_fk
    ON logistics.rider_location_pings (brand_id);

-- bucket S: soft pointer — parent may be deleted/cancelled (src 05_bc5_logistics.sql:125)
DO $$ BEGIN
    ALTER TABLE logistics.rider_location_pings
        ADD CONSTRAINT rider_location_pings_current_assignment_id_fkey
        FOREIGN KEY (current_assignment_id)
        REFERENCES logistics.rider_assignments(id)
        ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_rider_location_pings_current_assignment_id_fk
    ON logistics.rider_location_pings (current_assignment_id);

-- ---- logistics.riders ---------------------------------------------------
-- bucket 2: tenant scoping (src 05_bc5_logistics.sql:26)
DO $$ BEGIN
    ALTER TABLE logistics.riders
        ADD CONSTRAINT riders_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_riders_brand_id_fk
    ON logistics.riders (brand_id);

-- bucket 2: tenant scoping (src 05_bc5_logistics.sql:27)
DO $$ BEGIN
    ALTER TABLE logistics.riders
        ADD CONSTRAINT riders_franchise_id_fkey
        FOREIGN KEY (franchise_id)
        REFERENCES tenancy_org.franchises(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_riders_franchise_id_fk
    ON logistics.riders (franchise_id);

