-- ===========================================================================
-- FK patch — schema 'engagement_cms'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- engagement_cms.notification_preferences ----------------------------
-- bucket 2: tenant scoping (src 08_bc8_engagement_cms.sql:69)
DO $$ BEGIN
    ALTER TABLE engagement_cms.notification_preferences
        ADD CONSTRAINT notification_preferences_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_notification_preferences_brand_id_fk
    ON engagement_cms.notification_preferences (brand_id);

-- ---- engagement_cms.notifications_log -----------------------------------
-- bucket 3: tenant scoping (partitioned referencing table) (src 08_bc8_engagement_cms.sql:150)
DO $$ BEGIN
    ALTER TABLE engagement_cms.notifications_log
        ADD CONSTRAINT notifications_log_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_notifications_log_brand_id_fk
    ON engagement_cms.notifications_log (brand_id);

-- bucket S: soft pointer — parent may be deleted/cancelled (src 08_bc8_engagement_cms.sql:151)
DO $$ BEGIN
    ALTER TABLE engagement_cms.notifications_log
        ADD CONSTRAINT notifications_log_outbox_id_fkey
        FOREIGN KEY (outbox_id)
        REFERENCES engagement_cms.notifications_outbox(id)
        ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_notifications_log_outbox_id_fk
    ON engagement_cms.notifications_log (outbox_id);

-- ---- engagement_cms.notifications_outbox --------------------------------
-- bucket 2: tenant scoping (src 08_bc8_engagement_cms.sql:99)
DO $$ BEGIN
    ALTER TABLE engagement_cms.notifications_outbox
        ADD CONSTRAINT notifications_outbox_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_notifications_outbox_brand_id_fk
    ON engagement_cms.notifications_outbox (brand_id);

-- ---- engagement_cms.whatsapp_message_log --------------------------------
-- bucket 2: tenant scoping (src 08_bc8_engagement_cms.sql:185)
DO $$ BEGIN
    ALTER TABLE engagement_cms.whatsapp_message_log
        ADD CONSTRAINT whatsapp_message_log_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_whatsapp_message_log_brand_id_fk
    ON engagement_cms.whatsapp_message_log (brand_id);

-- bucket 1: domain cross-aggregate link (src 08_bc8_engagement_cms.sql:187)
DO $$ BEGIN
    ALTER TABLE engagement_cms.whatsapp_message_log
        ADD CONSTRAINT whatsapp_message_log_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customer_catalog.customers(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_whatsapp_message_log_customer_id_fk
    ON engagement_cms.whatsapp_message_log (customer_id);

-- bucket 1: domain cross-aggregate link (src 08_bc8_engagement_cms.sql:188)
DO $$ BEGIN
    ALTER TABLE engagement_cms.whatsapp_message_log
        ADD CONSTRAINT whatsapp_message_log_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES identity_access.users(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_whatsapp_message_log_user_id_fk
    ON engagement_cms.whatsapp_message_log (user_id);

