-- ===========================================================================
-- FK patch — schema 'kernel'
-- ===========================================================================
-- Auto-generated by db/tools/generate_fk_patches.py
-- Bucket legend:
--   1 = domain cross-aggregate link        → RESTRICT
--   2 = tenant scoping (non-partitioned)   → RESTRICT
--   3 = tenant scoping (partitioned)       → RESTRICT
--   C = aggregate child                    → CASCADE
--   S = soft pointer                       → SET NULL
-- All FKs schema-qualified; partitioned parents use composite (id, partition_col).
-- ===========================================================================

-- ---- kernel.file_attachments --------------------------------------------
-- bucket 2: tenant scoping (src 00_kernel.sql:135)
DO $$ BEGIN
    ALTER TABLE kernel.file_attachments
        ADD CONSTRAINT file_attachments_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_file_attachments_brand_id_fk
    ON kernel.file_attachments (brand_id);

-- ---- kernel.outbox_events -----------------------------------------------
-- bucket 2: tenant scoping (src 00_kernel.sql:179)
DO $$ BEGIN
    ALTER TABLE kernel.outbox_events
        ADD CONSTRAINT outbox_events_brand_id_fkey
        FOREIGN KEY (brand_id)
        REFERENCES tenancy_org.brands(id)
        ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_outbox_events_brand_id_fk
    ON kernel.outbox_events (brand_id);

